// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface About {
  id: string;
  slug: string | null;
  status: string;
  heading?: string;
  bio_paragraph_1?: string;
  bio_paragraph_2?: string;
  quote?: string;
  closing_statement?: string;
  photo_url?: string;
  photo_alt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface AboutOffClockNotes {
  id: string;
  slug: string | null;
  status: string;
  label?: string;
  value?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface AboutPersonalityCards {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  description?: string;
  icon?: string;
  accent_color?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface AboutStats {
  id: string;
  slug: string | null;
  status: string;
  value?: string;
  label?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Connect {
  id: string;
  slug: string | null;
  status: string;
  quote?: string;
  photo_url?: string;
  photo_alt?: string;
  contact_items?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Experience {
  id: string;
  slug: string | null;
  status: string;
  section_heading?: string;
  section_subheading?: string;
  cta_heading?: string;
  cta_subheading?: string;
  headshot_url?: string;
  headshot_alt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ExperienceRoles {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  company?: string;
  division?: string;
  dates?: string;
  era?: string;
  side?: string;
  icon_type?: string;
  highlights?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ExperienceStats {
  id: string;
  slug: string | null;
  status: string;
  value?: string;
  label?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Hero {
  id: string;
  slug: string | null;
  status: string;
  badge_text?: string;
  headline?: string;
  subheading?: string;
  cta_text?: string;
  headshot_url?: string;
  headshot_alt?: string;
  resume_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  published_date?: string;
  tags?: string;
  cover_image_url?: string;
  cover_image_alt?: string;
  body?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Projects {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  description?: string;
  tags?: string;
  href?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface WhatIDoColumns {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  bullets?: string;
  icon_type?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about: About;
    about_off_clock_notes: AboutOffClockNotes;
    about_personality_cards: AboutPersonalityCards;
    about_stats: AboutStats;
    connect: Connect;
    experience: Experience;
    experience_roles: ExperienceRoles;
    experience_stats: ExperienceStats;
    hero: Hero;
    pages: Page;
    posts: Post;
    projects: Projects;
    what_i_do_columns: WhatIDoColumns;
  }
}